name: Run Unit Tests

on: 
  push:
    path: 'nodejs/3/project'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test